# Augmentation configuration
# Controls how events and reasoning traces are augmented

# Event title augmentation settings
event:
  # Whether to run event augmentation
  enabled: true
  # Model to use for event augmentation
  model: "openai/gpt-5-mini"
  # Whether to use OpenRouter API
  use_openrouter: false
  # Batch size for event augmentation
  batch_size: 100
  # Timeout per batch (seconds)
  timeout: 180

# Reasoning trace augmentation settings
reasoning:
  # Whether to run reasoning augmentation
  enabled: true
  # Models to use for reasoning augmentation
  # Each trace will be augmented by one or more of these models
  models:
    - "openai/gpt-5-mini"
    - "google/gemini-3-flash-preview"
  # Whether to use OpenRouter API
  use_openrouter: true
  # Batch size for processing
  batch_size: 100
  # Timeout per request (seconds)
  timeout: 200
  
  # Used for instantiating the augmentation strategy class
  strategy:
    _target_: prophet_hindsight.reasoning.augment_strategies.UniformRandomStrategy
    overlap: true
    fraction: 0.6
    seed: 2025

